Bump PostCSS to 8.3, resolving CVE-2021-23368
gulp-sourcemaps/identity-map pull request #12
Opened 2021-06-05 16:28 UTC by TempixTL

Fixes PostCSS ReDoS vulnerability. See https://www.npmjs.com/advisories/1693

All tests run using `npm run test` pass. At a glance, it doesn't look like there are any relevant breaking changes in the [PostCSS 8.0.0 release notes](https://github.com/postcss/postcss/releases/tag/8.0.0).

2021-06-05 16:36 UTC, TempixTL commented
Looks like the CI for Node v6 failed. This is probably due to one of PostCSS 8's breaking changes, which drop support for Node v6, among others:

> PostCSS 8 dropped Node.js 6.x, 8.x, 11.x, and 13.x versions support. All these versions have no security updates anymore.

*Pulled from [PostCSS 8.0.0 release notes](https://github.com/postcss/postcss/releases/tag/8.0.0) under "Breaking Changes".*

2021-11-09 11:43 UTC, niksy commented
What can we do to help to get this merged?

2024-05-15 13:14 UTC, alex-voznyuk-kovaltchuk-sp approved these changes

2024-05-15 13:35 UTC, alex-voznyuk-kovaltchuk-sp requested changes
PostCSS to 8.4.38

2024-05-15 13:37 UTC, alex-voznyuk-kovaltchuk-sp approved these changes

2024-05-15 13:37 UTC, alex-voznyuk-kovaltchuk-sp commented on package.json
> +    "postcss": "^8.3.0",
```suggestion
    "postcss": "^8.4.38",
```

2024-05-15 13:42 UTC, alex-voznyuk-kovaltchuk-sp commented
@nmccready @tchetwin  @phated Could you please merge it and create a release?

2025-05-27 15:41 UTC, merged

2025-10-10 16:27 UTC, mjkent commented
@nmccready @tchetwin @phated @alex-voznyuk-kovaltchuk-sp Are there plans to do a new release(in GH and npmjs.com) for this?